
name: 'Install JVMCI, set JAVA_HOME and clone Graal'
runs:
  using: "composite"
  steps:
    - name: Install JVMCI
      run: jt install jvmci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$(jt install jvmci)" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Clone Graal
      run: jt mx sforceimports
      shell: bash
      working-directory: ${{ github.action_path }}