require_relative '../spec_helper'
require 'stringio'

# The following tables are excerpted from Programming Ruby: The Pragmatic Programmer's Guide'
# Second Edition by Dave Thomas, Chad Fowler, and Andy Hunt, page 319-22.
#
# Entries marked [r/o] are read-only and an error will be raised of the program attempts to
# modify them. Entries marked [thread] are thread local.

# Exception Information
# ---------------------------------------------------------------------------------------------------
#
# $!               Exception       The exception object passed to raise. [thread]
# $@               Array           The stack backtrace generated by the last exception. [thread]

# Pattern Matching Variables
# ---------------------------------------------------------------------------------------------------
#
# These variables are set to nil after an unsuccessful pattern match.
#
# $&               String          The string matched (following a successful pattern match). This variable is
#                                  local to the current scope. [r/o, thread]
# $+               String          The contents of the highest-numbered group matched following a successful
#                                  pattern match. Thus, in "cat" =~/(c|a)(t|z)/, $+ will be set to “t”. This
#                                  variable is local to the current scope. [r/o, thread]
# $`               String          The string preceding the match in a successful pattern match. This variable
#                                  is local to the current scope. [r/o, thread]
# $'               String          The string following the match in a successful pattern match. This variable
#                                  